### ISSUE TITLE
Difficulties getting homie_device to start

### ISSUE THREAD

**Issue by thebeswick** [microhomie/microhomie#15]
I am very new to microhomie and having a few problems getting it running. I created a settings.py file and copied it across to my ESP device. I have successfully started WiFi and imported my settings but when I try and run 
`homie_device = HomieDevice(settings)`
I get the following error 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/homie/__init__.py", line 35, in __init__
AttributeError: 'module' object has no attribute 'DEVICE_STATS_INTERVAL'`

Any ideas? I am very keen to use this project

**Comment by kinkerl** [comment]
Hi. Did you copy the settings.example.py to settings.py and changed the values accordingly? 
The error suggests that the settings.py is missing the attribute DEVICE_STATS_INTERVAL

**Comment by thebeswick** [comment]
Hi,
Yes I did copy and edit the settings.py file and then copied it across to my root directory on my ESP device. I did find a couple of typos in the settings.py file and now everything seems to be working again. Thanks for your reply.
