### ISSUE TITLE
Full "properties" support is missing

### ISSUE THREAD

**Issue by bodiroga** [microhomie/microhomie#28]
Hi guys!

As far as I know, this implementation doesn't support Homie properties as defined in the Homie 3.0.1 specification: https://homieiot.github.io/specification/#properties

There is no option to define the property name, unit, datatype, format and if the property is retained or settable. Is this a known issue?

Thanks and best regards,

Aitor

**Comment by bodiroga** [comment]
Ok, I have seen that in the micropython-nodes repository, you are implementing the properties of a node "by hand". See the DHT22 as an example: https://github.com/microhomie/microhomie-nodes/blob/feature/homie_v3/dht22/homie/node/dht22.py

For the Homie-python project, I (and jalmeroth) created a Property class to stores this information (https://github.com/jalmeroth/homie-python/blob/5a8388dce13bf4e4e7811ab41e7a0c6e47d1b712/homie/property.py) and a couple of methods to add properties to a node (Node.addProperty()). Are you interested in having this functionality in microhomie? Hardcoding all "yield (b''dht22/temperature/$name', b'temperature')" attributes seems a little bit unnatural and, in my opinion, should be handled by the library.

**Comment by rroemhild** [comment]
Hey, sorry I'm a bit busy at the moment. Yes you have to publish all by yourself. I'm working on a async version of microhomie branch feature/asyncio, with a property class.

**Comment by rroemhild** [comment]
The async version is not finished, but I have a local running version I still need to merge an publish.

**Comment by bodiroga** [comment]
Hi @rroemhild!

Thanks for your fast answer and congratulations for the project, it works great in the first tests I've made.

So the idea it make the library fully async with the use of mqtt_as library, right? That sounds really great! I will try to test the asyncio branch and report any issue I find, although you have said that it is not ready yet 👍

**Comment by rroemhild** [comment]
Hi @bodiroga,

we're glad you like Microhomie. Yes the async version is based on mqtt_as fork from @kevinkk525. And so far I'm happy with the async version. I've made some updates to the branch, ready for testing :)

I'll close this issue and we can continue in #25 or join us on slack and send me a PM if  you need help with the async version. The `main.example.py` has a simple LED node updated to asyncio.

Kind regards
Rafael
