### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by palmtreefrb** [microhomie/microhomie#29]
Is there a plan to continue this project and work on the wifi reconnect issue? I noticed a branch asyncio that is using mqtt_as by Peter Hinch. Will the asyncio branch be merged soon?

Thanks,
Rick

**Comment by rroemhild** [comment]
Hi @palmtreefrb, thanks for your message an interest in Microhomie. The asyncio branch will be merged in the next days. There are some changes that will break existing Microhomie Devices and Nodes and with the asyncio version we're going to version 1.0.0. We just need to update the nodes or at least some of them and update the documentation :)

**Comment by palmtreefrb** [comment]
That is good news. For me evertyhing is worrking good so far. I took your node for dht22 and refactored and renamed it to work with the onewire ds18x20 temperature probe. It.  is working good as well. Thanks for your awesome project!!!
