### ISSUE TITLE
onewire node

### ISSUE THREAD

**Issue by palmtreefrb** [microhomie/microhomie#31]
I have been creating a prototype app and thought I would share this class for onewire DS18X20. I basically took the DHT22 node and modified it. Note: the below will only return the first sensor on the bus as onewire can have many sensors on one gpio. I can be quite easily be modified to enumerate all sensors.

import gc
import time

from ds18x20 import DS18X20
from onewire import OneWire
from machine import Pin
from homie.node import HomieNode

class DS18B20(HomieNode):

    def __init__(self, name="One Wire DS18B20", pin=12, interval=60, pull=-1):
        super(DS18B20, self).__init__(name=name, interval=interval)
        gc.collect()
        self.node_id = b"ds18b20"
        print('Pin=' + str(pin))
        self.ds18b20 = DS18X20(OneWire(Pin(pin)))
        addrs = self.ds18b20.scan()
        if not addrs:
            raise Exception('no DS18B20 found at bus on pin %d' % pin)
        # save what should be the only address found
        self.addr = addrs.pop()

        self.temperature = 0

    def __str__(self):
        return 'DS18B20: Temperature = {}'.format(
            self.temperature)

    def get_properties(self):
        yield (b"ds18b20/$name", self.name)
        yield (b'ds18b20/$type', b'DS81B20')
        yield (b'ds18b20/$properties', b'temperature')

        # temperature
        yield (b'ds18b20/temperature/$name', b'Temperature')
        yield (b'ds18b20/temperature/$unit', b'°F')
        yield (b'ds18b20/temperature/$datatype', b'float')
        yield (b'ds18b20/temperature/$format', b'-40:80')

    def update_data(self):
        self.temperature = self.read_temp()

    def get_data(self):
        yield (b'ds18b20/temperature', self.temperature)

    def read_temp(self, fahrenheit=True):
        """
        Reads temperature from a single DS18X20
        :param fahrenheit: Whether or not to return value in Fahrenheit
        :type fahrenheit: bool
        :return: Temperature
        :rtype: float
        """
        self.ds18b20.convert_temp()
        time.sleep_ms(750)
        temp = self.ds18b20.read_temp(self.addr)
        if fahrenheit:
            ntemp = temp
            print('Temp: ' + str(self.c_to_f(ntemp)))
            return self.c_to_f(ntemp)
        return temp

    @staticmethod
    def c_to_f(c):
        """
        Converts Celsius to Fahrenheit
        :param c: Temperature in Celsius
        :type c: float
        :return: Temperature in Fahrenheit
        :rtype: float
        """
        return (c * 1.8) + 32

**Comment by rroemhild** [comment]
Great work and thanks for the share! With the next release, Microhomie use asyncio and has significant changes in node and property handling. It would be great if you can refactore your code to fit with the feature/asyncio branch. We will merge this branch to master tomorrow and release an alpha image.

**Comment by palmtreefrb** [comment]
Here is the refactored node for one wire ds18b20 temperature sensor...

import time

from ds18x20 import DS18X20
from onewire import OneWire

from machine import Pin
from uasyncio import get_event_loop, sleep_ms

from homie.node import HomieNode
from homie.property import HomieNodeProperty


class DS18B20(HomieNode):

    def __init__(self, name="One Wire DS18B20", pin=12, interval=10, pull=-1):
        super().__init__(id="ds18b20", name=name, type="ds18b20")
        self.ds18b20 = DS18X20(OneWire(Pin(pin)))
        addrs = self.ds18b20.scan()
        if not addrs:
            raise Exception('no DS18B20 found at bus on pin %d' % pin)
        # save what should be the only address found
        self.addr = addrs.pop()

        self.temperature = 0

        self.interval = interval

        self.temp_property = HomieNodeProperty(
            id="temperature",
            name="Temperature",
            datatype="float",
            format="-40:80",
            unit="°F",
        )
        self.add_property(self.temp_property)

        loop = get_event_loop()
        loop.create_task(self.update_data())

    async def update_data(self):
        delay = self.interval * 1000

        while True:
            self.temperature = self.read_temp()
            self.temp_property.data = self.temperature
            await sleep_ms(delay)

    def read_temp(self, fahrenheit=True):
        """
        Reads temperature from a single DS18X20
        :param fahrenheit: Whether or not to return value in Fahrenheit
        :type fahrenheit: bool
        :return: Temperature
        :rtype: float
        """
        self.ds18b20.convert_temp()
        time.sleep_ms(750)
        temp = self.ds18b20.read_temp(self.addr)
        if fahrenheit:
            ntemp = temp
            print('Temp: ' + str(self.c_to_f(ntemp)))
            return self.c_to_f(ntemp)
        return temp

    @staticmethod
    def c_to_f(c):
        """
        Converts Celsius to Fahrenheit
        :param c: Temperature in Celsius
        :type c: float
        :return: Temperature in Fahrenheit
        :rtype: float
        """
        return (c * 1.8) + 32


if __name__ == "__main__":
    main()

**Comment by rroemhild** [comment]
Thanks for your contribution. I've added your example to the example directory.
