### ISSUE TITLE
ESP32: Build firmware or just install all the requierements?

### ISSUE THREAD

**Issue by rroemhild** [microhomie/microhomie#33]
Test the ESP32 device with Microhomie. Is it just enough to copy all files to the device or should we build a firmware for the ESP32?

**Comment by palmtreefrb** [comment]
I have an LOLIN D32 Pro V2.0.0 and it is running good with latest standard micropython build and just copying all the files.

**Comment by rroemhild** [comment]
Thanks @palmtreefrb! I add an esp32 section to the docs and an mpfshell install script.
