### ISSUE TITLE
Relais Node not being restored

### ISSUE THREAD

**Issue by palmtreefrb** [microhomie/microhomie#34]
The 1.0.0 (asyncio version) Relay node is not being restored after restarting the esp8266. In my case I have two relays relay_0 and relay_1 and on restart neither one is restored.
        self.relay_property = HomieNodeProperty(
            id="power",
            name="Relay",
            settable=True,
            retained=True,
            datatype="bool",
            default=TRUE,
            restore=True,
            range=2,
        )

**Comment by rroemhild** [comment]
Fixed in alpha3 release. Thanks for testing & reporting!
