### ISSUE TITLE
BerkelyDB library 

### ISSUE THREAD

**Issue by palmtreefrb** [microhomie/microhomie#35]
What can I safely eliminate if I want to add back the BerkelyDB library? I will only be using relays and the onewire ds18b20 sensor.

>>> help('modules')
__main__          homie/__init__    os                uheapq
_boot             homie/constants   port_diag         uio
_onewire          homie/device      random            ujson
apa102            homie/node        re                uos
array             homie/property    select            upip
aswitch           homie/utils       socket            upip_utarfile
asyn              inisetup          ssl               urandom
binascii          io                struct            ure
builtins          json              sys               uselect
collections       lwip              time              usocket
dht               machine           uasyncio/__init__ ussl
ds18x20           math              uasyncio/core     ustruct
errno             micropython       ubinascii         utime
esp               mqtt_as           ucollections      utimeq
flashbdev         neopixel          ucryptolib        uzlib
framebuf          network           uctypes           websocket
gc                ntptime           uerrno            websocket_helper
hashlib           onewire           uhashlib          zlib

**Comment by rroemhild** [comment]
upip, upip_utarfile, neopixel, aswitch, dht

**Comment by rroemhild** [comment]
I just enabled `MICROPY_PY_BTREE` and the build passed :) So try to enable BTREE first and then remove if it does not work. Maybe we can re-enable it in general.

**Comment by palmtreefrb** [comment]
I was able to build it successfully. Great work, Thanks!!!
