### ISSUE TITLE
ESP32 OSError 119 writing to the socket

### ISSUE THREAD

**Issue by palmtreefrb** [microhomie/microhomie#36]
I have experienced this issue with ESP32. You can read about it here...
https://github.com/micropython/micropython-esp32/issues/166

Seems there is a new version of mqtt_as published about a month ago that checks for this condition.

**Comment by rroemhild** [comment]
Hi @palmtreefrb, we use the `mqtt_as_minimal.py ` from @kevinkk525 `[fork](https://github.com/kevinkk525/micropython-mqtt) to save some space on the esp8266. `mqtt_as.py` should solve this problem.

**Comment by kevinkk525** [comment]
The new version of mqtt_as published by pythoncoder is just an attempt to support the pyboard D and doesn't include some features I added (like unsubscribe). The workarounds for the Esp32 were included earlier and are present in mqtt_as in my fork.

**Comment by palmtreefrb** [comment]
Ok, I deployed mqtt_as_minimal.py fork and it is working now.
Thanks...

**Comment by kevinkk525** [comment]
The minimal version is not for the Esp32.

**Comment by rroemhild** [comment]
Add a node to the docs, that for esp32 the full mqtt_as.py version is needed.
