### ISSUE TITLE
WDT is Awesome, but...

### ISSUE THREAD

**Issue by palmtreefrb** [microhomie/microhomie#40]
It can be frustrating during development etc. So I added a setting and code to bypass WDT during testing/debugging.

settings.py
DEBUG = False

device.py
class HomieDevice:
    def __init__(self, settings):
        self.debug = getattr(settings, "DEBUG", False)
...
...
        if self._first_start is True:
            await self.publish_properties()
            self._first_start = False

            # activate WDT
            if self.debug is not True:
                loop = get_event_loop()
                loop.create_task(self.wdt())

            # start coros waiting for ready state
            _EVENT.set()
            await sleep_ms(MAIN_DELAY)
            _EVENT.clear()

        await self.publish(DEVICE_STATE, STATE_READY)
  
main.py
    homie = HomieDevice(settings)
    homie.debug = True

**Comment by rroemhild** [comment]
You are right, WDT makes it hard to develop and debug. I'll add the debug option. Thanks.

**Comment by rroemhild** [comment]
Fixed issue in v2.1.0.
