### ISSUE TITLE
Upgrade to MICROPYVERSION = 1.12

### ISSUE THREAD

**Issue by dmartinpro** [microhomie/microhomie#41]
Could you please take into account the new version of Micropython and build either a ESP8266 and ESP32 version of Microhomie?

**Comment by rroemhild** [comment]
I will, MicroPython has changed on how to build firmware with included freezed modules. I have to look at this and make some tests.

**Comment by rroemhild** [comment]
Updated to MicroPython 1.12 in development branch. I'll release a Microhomie v2.3 alpha firmware release for the esp8622 the next days.

**Comment by rroemhild** [comment]
v2.3.0 alpha1 is released. You may want to use the non ota version for now. OTA is not very well documented in the MicroPython docs. I'll add a section how to use OTA to the Microhomie documentation later.

**Comment by dmartinpro** [comment]
Thanks, going to test beta.1

**Comment by palmtreefrb** [comment]
Did you enable littlefs? Also, I have not tried building 1.12, do you have any tips or suggestions on building. I know about the frozen modules, but if you ran into any other issues I would appreciate the feedback.
Thanks for all your work on microhomie!!!

**Comment by rroemhild** [comment]
I have not looked into littlefs and compiled MicroPython with a clean repo. I just disabled btree support via the environment variable.

If littlefs is enabled in the repository by default it should be enabled too in the beta firmware.

The only issue compiling MicroPython was that the openesp tool, does not detect bash in version 5.
