### ISSUE TITLE
Publish all nodes on recovery

### ISSUE THREAD

**Issue by palmtreefrb** [microhomie/microhomie#42]
I want to publish all nodes if connection is lost and then recovered. What would be the best way to handle publishing all nodes if connection to broker is lost then reconnected?

**Comment by rroemhild** [comment]
Currently the device only publishes properties on first start. My idea behind this was that all properties are retained on the broker and on network recovery nothing changes on the device, so Microhomie saves time to come back to ready state.

You can switch the lines 149 and 150 in device.py to publish all properties after the device has reconnected to the broker.

**Comment by rroemhild** [comment]
Why do you need to re-publish all nodes on connection recovery? Maybe we can include this and make it optional.

**Comment by palmtreefrb** [comment]
Well, not a normal case, but I switched brokers and lost retained properties. I store properties in a json file that can be published to restore the broker. It is critical that my microhomie devices continue functioning without broker connections.

**Comment by rroemhild** [comment]
It's not that comfortable than auto re-publish but with the new version (in beta) you can send the payload `reset` to the topic homie/deviceid/$mpy to reset the device.

**Comment by palmtreefrb** [comment]
Great, I will take a look at the new "reset"
Thanks...
