### ISSUE TITLE
Get microhomie working on pycom's products (wipy, etc)

### ISSUE THREAD

**Issue by arthurlutz** [microhomie/microhomie#44]
microhomie looks like a great project ! 

Any chance of getting it to work on pycom's versions of micropython ? https://docs.pycom.io/products/

I can personnaly help with the wipy which I have in stock and can contribute some documentation for that.

**Comment by rroemhild** [comment]
It should Work with pycom version 1.20. I have a FiPy but Not Tester since version 1.18, wich does not work. As far as I know v1.20 has included uasyncio libs and support. I'll test Microhomie with the latest pycom firmware on my FiPy device the next days.

**Comment by rroemhild** [comment]
Added basic support for the pycom boards and a example for the heartbeat led in the example folder. Had to patch mqtt_as.py to support the pycom boards and need to get this upstream.

**Comment by rroemhild** [comment]
Is your WiPy still in stock? My is :D Need some feedback before I'll push it upstream.

**Comment by arthurlutz** [comment]
@rroemhild sorry for not getting back to you on this one. Great news for the support. I'll be testing it in the next few days. (yes I still have wipy devices I can test on).

**Comment by arthurlutz** [comment]
I'm bumping into some `MemoryError` 

```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "homie/device.py", line 5, in <module>
  File "homie/utils.py", line 11, in <module>
MemoryError: memory allocation failed, allocating 136 bytes
Pycom MicroPython 1.20.0.rc1 [v1.9.4-bc4d7d0] on 2018-12-12; WiPy with ESP32
```

It seem to be on the loading of `mqtt_as.py` which seems to be confirmed by : 

```
>>> import lib.mqtt_as
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: memory allocation failed, allocating 136 bytes
```

Weirdly if I do : 
```
>>> import mqtt_as
>>> mqtt_as
<module 'mqtt_as' from '/flash/lib/mqtt_as.py'>
```
it works, so it might be something else.

**Comment by rroemhild** [comment]
I've add Pycom support to the v2 branch old Microhomie version. Pycom's pybytes is still based on MicroPython v1.11 with has no support for the new asyncio v3 introduced in MicroPython v1.13. So I'll keeping this with the on Microhomie version.

You can try the Pycom heartbeat example, that works for me with Pycom MicroPython v1.20.2.r1 and LittleFS.
