### ISSUE TITLE
Device.py raises error for Linux device ID

### ISSUE THREAD

**Issue by yeshuawatso** [microhomie/microhomie#52]
At the line: https://github.com/microhomie/microhomie/blob/67324a9ff581758439a3849413aaf810cab01304/homie/device.py#L82
the function get_unique_id() is evaluated prior to the attribute being searched, the standard nature of Python. This function raises an error if running on a Linux platform that prevents further execution with the ironic message to "...Provide the DEVICE_ID option in your settings.py." Even if this value exists in the settings.py (or any other equivalent object), it'll never be used because of the raised error.

Resolution: possibly using a lazy equivalency such as  `self.device_id = getattr(settings, "DEVICE_ID", None) or get_unique_id()` since False, 0, and None or invalid device IDs anyway?

**Comment by rroemhild** [comment]
Indeed that's ironical :facepalm: Thanks for reporting. I think about to just return a default device ID if running on a Linux platform and log it to the REPL as a warning. Logging module is planed for the next release.

**Comment by rroemhild** [comment]
Another approach could be to try to get the hostname from the environment and use this as the device id. If no HOSTNAME in env return a default id. Not unique but I think that's better than just return the default id.
