### ISSUE TITLE
reconnect behavior

### ISSUE THREAD

**Issue by untzag** [microhomie/microhomie#53]
Hi---thanks for this project it's been really helped me :smiling_face_with_three_hearts:

I'm using microhomie on an ESP8266 with microhomie v3.0.2. Sometimes my WiFi goes down. Currently when this happens my device goes offline permanently until I manually reset it. I'm hoping to change this so the device periodically tries to reconnect until it finds WiFi again. As a micropython novice I'm struggling a bit to think about how to best do this.

My first thought would be to use a watchdog that I feed when the connection is good, but I see that you explicitly create a wdt task.

Any advice would be appreciated. Thanks again, I'm really loving homie and micropython.

**Comment by rroemhild** [comment]
Hi @untzag,

glad you like Microhomie. In Microhomie the [mqtt_as](https://github.com/peterhinch/micropython-mqtt/blob/c9628ee4d2d18580a09cccbb0b68eb5144c690d3/mqtt_as/mqtt_as.py#L600) module handle automatic recovery from WiFi and broker outages. This works great for my devices so far.

You can activate debug logging for the mqtt_as module. Import mqtt_as into your main and set `DEBUG=True`:

```
import mqtt_as
mqtt_as.MQTT_base.DEBUG = True
```

**Comment by untzag** [comment]
Thanks @rroemhild, your debugging techniques helped me. The recovery works actually, but at some point after recovering a few times my device runs out of memory. Doesn't seem to have a memory leak during normal operation. I'll have to follow that path now.
